### ISSUE TITLE
Method does not exist when calling Check.satisfies() in Pydeequ 1.1.1 / Deequ 2.0.4

### ISSUE THREAD

**Issue by eolvwa** [awslabs/python-deequ#160] opened 2023-10-03 13:40 UTC
The Check.satisfies method appears to be incompatible with Deequ 2.0.4.  That release of Deequ includes a new optional `columns` parameter for the Check.satisfies() function per [PR 478](https://github.com/awslabs/deequ/pull/478/files#diff-3262b920e589bf164c4570e14603cf7fdcf4c5ac9819f4e092dc81344d52cb42R687).

**To Reproduce**
Run the following code:
```python
from pydeequ import *
check = Check(spark, CheckLevel.Warning, "Test")
check.satisfies("Field == 1", "Field", lambda x: x == 1, "Field should be equal to 1")
```

**Expected behavior**
A new compliance constraint is added to the check.

**Actual behavior**
Py4J reports a missing method:
```
Py4JError: An error occurred while calling o31.satisfies. Trace:
py4j.Py4JException: Method satisfies([class java.lang.String, 
class java.lang.String, class com.sun.proxy.$Proxy16, class scala.Some]) does not exist
```

**Versions**
 - Spark: 3.0.1
 - PyDeequ 1.1.1
 - Deequ 2.0.4 (deequ-2.0.4-spark-3.3)

**Additional context**
As a workaround, it looks like one can hotpatch the code.  I'm not very familiar with Py4J, Pydeequ, or Deequ so not sure if this is the best long-term solution:

```python
# assume `spark` is in scope and is the current spark session
from pydeequ import Check, CheckLevel
from pydeequ.analyzers import AnalysisRunner
from pydeequ.scala_utils import ScalaFunction1, to_scala_seq
from pydeequ.verification import VerificationSuite

# modified version
def new_satisfies(self, columnCondition, constraintName, assertion=None, hint=None):
    assertion_func = (
            ScalaFunction1(self._spark_session.sparkContext._gateway, assertion)
            if assertion
            else getattr(self._Check, "satisfies$default$2")()
        )
    hint = self._jvm.scala.Option.apply(hint)
    cols = to_scala_seq(self._jvm, [])
    y = getattr(self._jvm.scala.collection.TraversableOnce, "toList$")
    cols = y(cols)
    self._Check = self._Check.satisfies(columnCondition, constraintName, assertion_func, hint, cols)
    return self   

# install
Check.satisfies = new_satisfies

# try out
check = Check(spark, CheckLevel.Warning, "Test")
check = check.satisfies("X == 2", "X", lambda x: x == 1, "X")

r = AnalysisRunner(spark)
df = spark.createDataFrame([{"X": 3}, {"X": 2}])
res = (VerificationSuite(spark)
            .onData(df)
            .addCheck(check)
            .run())
res.successMetricsAsDataFrame(spark, res).show()
```

**Comment by chenliu0831** [comment] 2023-10-04 00:22
Thanks for reporting - PyDeequ should change and fix this. Likely this is not covered by the test as well.

**Comment by chenliu0831** [comment] 2023-10-26 23:20
Actually I cannot reproduce this with `SPARK_VERSION=3.3` and `com.amazon.deequ:deequ:2.0.3-spark-3.3`. 

deequ 2.0.4 is not supported

**Comment by chenliu0831** [comment] 2024-04-12 16:03
This will be resolved in next release which will include https://github.com/awslabs/python-deequ/issues/169.

**Closed by chenliu0831** 2024-04-12 16:03 UTC
Labels: bug, dependencies
